### ISSUE TITLE
prompt module on tty

### ISSUE THREAD

**Issue by linhvng** [zimfw/zimfw#95] opened 2016-10-13 15:03 UTC
Please check the existing issues to make sure you're not duplicating a report.

For bug reports, please provide the following information:
- Zim commit ref:
- gist of .zimrc:
- Zsh version: 5.2
- gist of .zshrc:
- $(uname -mosr):
## Description

The prompt module on tty doesn't work, there's no theme at all. However, if I run tmux in tty, the prompt module works fine. Is this an expected behavior?
## Steps to reproduce
- Fresh installation of Arch Linux, no X-org, just tty.
- run: prompt -l
- Install tmux, using tmux in tty.
- run: prompt -l
## Images or other information

with tmux
![with_tmux](https://cloud.githubusercontent.com/assets/8838571/19354344/5a68bb6a-9134-11e6-8375-21e11d9b2de4.PNG)

without tmux
![without_tmux](https://cloud.githubusercontent.com/assets/8838571/19354343/5a6501aa-9134-11e6-9f85-7e8210263620.PNG)

**Comment by Eriner** [comment] 2016-10-22 20:10
This is the intended behavior. On a TTY load, it will source the `.zlogin` file, which will `zcompile` and prep some zim things. Once you get an interactive shell (after starting your X server), it should NOT read `.zlogin`, but rather `.zshrc`.

If you really want to have zim on a tty, just `source .zshrc`.

**Comment by Eriner** [comment] 2018-11-25 18:08
Try installing using the instructions on the Readme; I do not support the zim-git package in the AUR.

**Comment by DoTheEvo** [comment] 2018-11-25 18:49
alright, after few attempts I got it installed as according to instructions
it does feel bit unnecessary complicated but I guess arch AUR spoiled me

Anyway I now tried `source .zshrc` and `source /home/user/.zshrc` but still nothing

when I ssh in I get the nice prompt and I can choose
when I just go directly through virtual machine I get just hostname%

its not that big of a deal since i feared that through ssh it would be missing too
but consistency would be nice

**Comment by Eriner** [comment] 2018-11-25 19:03
Okay, I just switched to a second TTY and can reproduce the symptoms. The configuration works as expected (and .zshrc is sourced on TTY login), however the prompt does not work.

I'm going to re-open this issue as it is indeed a bug, however I view this as a low priority bug; who's really doing work in a TTY?

Low-priority issue which we should fix eventually, probably. That said, I'd bet that there are a lot of small issues that would prevent this from being fixed without a lot of effort, but I don't know that for sure. I am in no way motivated to fix this.

**Comment by ericbn** [comment] 2020-04-05 20:12
We deprecated the prompt module. So closing this.

**Closed by ericbn** 2020-04-05 20:12 UTC
Labels: bug, wontfix
